CREATE TABLE IF NOT EXISTS "request_directions" (
  "id" text PRIMARY KEY, "code" text NOT NULL UNIQUE, "name" text NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL
);
INSERT INTO "request_directions" ("id","code","name") VALUES
 ('req-dir-technical','technical','Технические'), ('req-dir-management','management','Менеджмент / аренда'),
 ('req-dir-accounting','accounting','Бухгалтерия'), ('req-dir-legal','legal','Юриспруденция'),
 ('req-dir-documents','documents','Документы'), ('req-dir-access','access','Доступ'), ('req-dir-other','other','Другое')
ON CONFLICT ("code") DO UPDATE SET "name"=EXCLUDED."name", "updated_at"=now();

CREATE TABLE IF NOT EXISTS "request_category_routes" (
  "category_id" text PRIMARY KEY REFERENCES "request_categories"("id") ON DELETE CASCADE,
  "direction_id" text NOT NULL REFERENCES "request_directions"("id") ON DELETE RESTRICT
);
INSERT INTO "request_category_routes" ("category_id","direction_id")
SELECT c.id, d.id FROM "request_categories" c JOIN "request_directions" d ON d.code = CASE
 WHEN c.code IN ('repair','electricity','plumbing','refit') THEN 'technical'
 WHEN c.code IN ('access','loading') THEN 'access'
 WHEN c.code='accounting' THEN 'accounting' WHEN c.code='legal' THEN 'legal'
 WHEN c.code='documents' THEN 'documents' ELSE 'other' END
ON CONFLICT ("category_id") DO UPDATE SET "direction_id"=EXCLUDED."direction_id";

ALTER TABLE "requests" ADD COLUMN IF NOT EXISTS "request_number" bigint GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS "requests_number_uq" ON "requests"("request_number");
ALTER TABLE "requests" ADD COLUMN IF NOT EXISTS "direction_id" text REFERENCES "request_directions"("id") ON DELETE RESTRICT;
UPDATE "requests" r SET "direction_id"=m."direction_id" FROM "request_category_routes" m WHERE m."category_id"=r."category_id" AND r."direction_id" IS NULL;
ALTER TABLE "requests" ALTER COLUMN "direction_id" SET NOT NULL;

CREATE TABLE IF NOT EXISTS "request_events" (
  "id" text PRIMARY KEY, "request_id" text NOT NULL REFERENCES "requests"("id") ON DELETE CASCADE,
  "event_type" text NOT NULL CHECK ("event_type" IN ('created','status_changed','assignee_changed','direction_changed','closed')),
  "actor_user_id" text REFERENCES "users"("id") ON DELETE SET NULL,
  "from_value" text, "to_value" text, "created_at" timestamptz DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS "request_events_request_idx" ON "request_events"("request_id","created_at");
INSERT INTO "request_events" ("id","request_id","event_type","actor_user_id","created_at")
SELECT md5('created:'||r.id),r.id,'created',r.created_by_user_id,r.created_at FROM "requests" r
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "permissions" ("id","code","name") VALUES
 ('perm-requests-view','requests.view','Просмотр заявок'), ('perm-requests-manage','requests.manage','Управление заявками')
ON CONFLICT ("code") DO UPDATE SET "name"=EXCLUDED."name", "updated_at"=now();
INSERT INTO "roles" ("id","code","name") VALUES ('role-request-manager','request_manager','Сотрудник по заявкам')
ON CONFLICT ("code") DO UPDATE SET "name"=EXCLUDED."name", "updated_at"=now();
INSERT INTO "role_permissions" ("role_id","permission_id")
SELECT r.id,p.id FROM "roles" r CROSS JOIN "permissions" p WHERE r.code IN ('admin','request_manager') AND p.code IN ('requests.view','requests.manage')
ON CONFLICT DO NOTHING;
INSERT INTO "employees" ("id","user_id","job_title")
SELECT 'employee-'||md5(u.id),u.id,'Администратор' FROM "users" u JOIN "user_roles" ur ON ur.user_id=u.id JOIN "roles" r ON r.id=ur.role_id WHERE u.kind='employee' AND r.code='admin'
ON CONFLICT ("user_id") DO NOTHING;
