/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as RentRouteImport } from './routes/rent'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ObjectsIndexRouteImport } from './routes/objects/index'
import { Route as ObjectsSlugRouteImport } from './routes/objects/$slug'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsSlugRoute = ObjectsSlugRouteImport.update({
  id: '/objects/$slug',
  path: '/objects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/favorites': typeof FavoritesRoute
  '/rent': typeof RentRoute
  '/sale': typeof SaleRoute
  '/services': typeof ServicesRoute
  '/objects/$slug': typeof ObjectsSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/objects/': typeof ObjectsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/favorites': typeof FavoritesRoute
  '/rent': typeof RentRoute
  '/sale': typeof SaleRoute
  '/services': typeof ServicesRoute
  '/objects/$slug': typeof ObjectsSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/objects': typeof ObjectsIndexRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/favorites': typeof FavoritesRoute
  '/rent': typeof RentRoute
  '/sale': typeof SaleRoute
  '/services': typeof ServicesRoute
  '/objects/$slug': typeof ObjectsSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/objects/': typeof ObjectsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/favorites'
    | '/rent'
    | '/sale'
    | '/services'
    | '/objects/$slug'
    | '/properties/$slug'
    | '/objects/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/favorites'
    | '/rent'
    | '/sale'
    | '/services'
    | '/objects/$slug'
    | '/properties/$slug'
    | '/objects'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/favorites'
    | '/rent'
    | '/sale'
    | '/services'
    | '/objects/$slug'
    | '/properties/$slug'
    | '/objects/'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FavoritesRoute: typeof FavoritesRoute
  RentRoute: typeof RentRoute
  SaleRoute: typeof SaleRoute
  ServicesRoute: typeof ServicesRoute
  ObjectsSlugRoute: typeof ObjectsSlugRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$slug': {
      id: '/objects/$slug'
      path: '/objects/$slug'
      fullPath: '/objects/$slug'
      preLoaderRoute: typeof ObjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FavoritesRoute: FavoritesRoute,
  RentRoute: RentRoute,
  SaleRoute: SaleRoute,
  ServicesRoute: ServicesRoute,
  ObjectsSlugRoute: ObjectsSlugRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
