/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as RentRouteImport } from './routes/rent'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountActivateRouteImport } from './routes/account/activate'
import { Route as AccountChangePasswordRouteImport } from './routes/account/change-password'
import { Route as AccountForgotPasswordRouteImport } from './routes/account/forgot-password'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AccountUtilitiesRouteImport } from './routes/account/utilities'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdsRouteImport } from './routes/admin/ads'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminMailingsRouteImport } from './routes/admin/mailings'
import { Route as AdminPremisesRouteImport } from './routes/admin/premises'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminStatisticsRouteImport } from './routes/admin/statistics'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminTenantsRouteImport } from './routes/admin/tenants'
import { Route as AdminUtilitiesRouteImport } from './routes/admin/utilities'
import { Route as ObjectsIndexRouteImport } from './routes/objects/index'
import { Route as ObjectsSlugRouteImport } from './routes/objects/$slug'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties/$slug'
import { Route as AccountDocumentsIdRouteImport } from './routes/account/documents/$id'
import { Route as AdminDocumentsUploadRouteImport } from './routes/admin/documents/upload'
import { Route as AdminPremisesUploadRouteImport } from './routes/admin/premises/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountActivateRoute = AccountActivateRouteImport.update({
  id: '/account/activate',
  path: '/account/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountChangePasswordRoute = AccountChangePasswordRouteImport.update({
  id: '/account/change-password',
  path: '/account/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/account/forgot-password',
  path: '/account/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountUtilitiesRoute = AccountUtilitiesRouteImport.update({
  id: '/account/utilities',
  path: '/account/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMailingsRoute = AdminMailingsRouteImport.update({
  id: '/admin/mailings',
  path: '/admin/mailings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPremisesRoute = AdminPremisesRouteImport.update({
  id: '/admin/premises',
  path: '/admin/premises',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/admin/statistics',
  path: '/admin/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtilitiesRoute = AdminUtilitiesRouteImport.update({
  id: '/admin/utilities',
  path: '/admin/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsSlugRoute = ObjectsSlugRouteImport.update({
  id: '/objects/$slug',
  path: '/objects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDocumentsIdRoute = AccountDocumentsIdRouteImport.update({
  id: '/account/documents/$id',
  path: '/account/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsUploadRoute = AdminDocumentsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminDocumentsRoute,
} as any)
const AdminPremisesUploadRoute = AdminPremisesUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminPremisesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/favorites': typeof FavoritesRoute
  '/rent': typeof RentRoute
  '/sale': typeof SaleRoute
  '/services': typeof ServicesRoute
  '/account/activate': typeof AccountActivateRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/utilities': typeof AccountUtilitiesRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/documents': typeof AdminDocumentsRouteWithChildren
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/mailings': typeof AdminMailingsRoute
  '/admin/premises': typeof AdminPremisesRouteWithChildren
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/utilities': typeof AdminUtilitiesRoute
  '/objects/$slug': typeof ObjectsSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/objects/': typeof ObjectsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/account/documents/$id': typeof AccountDocumentsIdRoute
  '/admin/documents/upload': typeof AdminDocumentsUploadRoute
  '/admin/premises/upload': typeof AdminPremisesUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/favorites': typeof FavoritesRoute
  '/rent': typeof RentRoute
  '/sale': typeof SaleRoute
  '/services': typeof ServicesRoute
  '/account/activate': typeof AccountActivateRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/utilities': typeof AccountUtilitiesRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/documents': typeof AdminDocumentsRouteWithChildren
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/mailings': typeof AdminMailingsRoute
  '/admin/premises': typeof AdminPremisesRouteWithChildren
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/utilities': typeof AdminUtilitiesRoute
  '/objects/$slug': typeof ObjectsSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/objects': typeof ObjectsIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/account/documents/$id': typeof AccountDocumentsIdRoute
  '/admin/documents/upload': typeof AdminDocumentsUploadRoute
  '/admin/premises/upload': typeof AdminPremisesUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/favorites': typeof FavoritesRoute
  '/rent': typeof RentRoute
  '/sale': typeof SaleRoute
  '/services': typeof ServicesRoute
  '/account/activate': typeof AccountActivateRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/utilities': typeof AccountUtilitiesRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/documents': typeof AdminDocumentsRouteWithChildren
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/mailings': typeof AdminMailingsRoute
  '/admin/premises': typeof AdminPremisesRouteWithChildren
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/utilities': typeof AdminUtilitiesRoute
  '/objects/$slug': typeof ObjectsSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/objects/': typeof ObjectsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/account/documents/$id': typeof AccountDocumentsIdRoute
  '/admin/documents/upload': typeof AdminDocumentsUploadRoute
  '/admin/premises/upload': typeof AdminPremisesUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/favorites'
    | '/rent'
    | '/sale'
    | '/services'
    | '/account/activate'
    | '/account/change-password'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/reset-password'
    | '/account/utilities'
    | '/admin/ads'
    | '/admin/announcements'
    | '/admin/documents'
    | '/admin/employees'
    | '/admin/leads'
    | '/admin/mailings'
    | '/admin/premises'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/statistics'
    | '/admin/support'
    | '/admin/tenants'
    | '/admin/utilities'
    | '/objects/$slug'
    | '/properties/$slug'
    | '/account/'
    | '/admin/'
    | '/objects/'
    | '/properties/'
    | '/account/documents/$id'
    | '/admin/documents/upload'
    | '/admin/premises/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/favorites'
    | '/rent'
    | '/sale'
    | '/services'
    | '/account/activate'
    | '/account/change-password'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/reset-password'
    | '/account/utilities'
    | '/admin/ads'
    | '/admin/announcements'
    | '/admin/documents'
    | '/admin/employees'
    | '/admin/leads'
    | '/admin/mailings'
    | '/admin/premises'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/statistics'
    | '/admin/support'
    | '/admin/tenants'
    | '/admin/utilities'
    | '/objects/$slug'
    | '/properties/$slug'
    | '/account'
    | '/admin'
    | '/objects'
    | '/properties'
    | '/account/documents/$id'
    | '/admin/documents/upload'
    | '/admin/premises/upload'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/favorites'
    | '/rent'
    | '/sale'
    | '/services'
    | '/account/activate'
    | '/account/change-password'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/reset-password'
    | '/account/utilities'
    | '/admin/ads'
    | '/admin/announcements'
    | '/admin/documents'
    | '/admin/employees'
    | '/admin/leads'
    | '/admin/mailings'
    | '/admin/premises'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/statistics'
    | '/admin/support'
    | '/admin/tenants'
    | '/admin/utilities'
    | '/objects/$slug'
    | '/properties/$slug'
    | '/account/'
    | '/admin/'
    | '/objects/'
    | '/properties/'
    | '/account/documents/$id'
    | '/admin/documents/upload'
    | '/admin/premises/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FavoritesRoute: typeof FavoritesRoute
  RentRoute: typeof RentRoute
  SaleRoute: typeof SaleRoute
  ServicesRoute: typeof ServicesRoute
  AccountActivateRoute: typeof AccountActivateRoute
  AccountChangePasswordRoute: typeof AccountChangePasswordRoute
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountUtilitiesRoute: typeof AccountUtilitiesRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminDocumentsRoute: typeof AdminDocumentsRouteWithChildren
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMailingsRoute: typeof AdminMailingsRoute
  AdminPremisesRoute: typeof AdminPremisesRouteWithChildren
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminStatisticsRoute: typeof AdminStatisticsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminUtilitiesRoute: typeof AdminUtilitiesRoute
  ObjectsSlugRoute: typeof ObjectsSlugRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  AccountDocumentsIdRoute: typeof AccountDocumentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/activate': {
      id: '/account/activate'
      path: '/account/activate'
      fullPath: '/account/activate'
      preLoaderRoute: typeof AccountActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/change-password': {
      id: '/account/change-password'
      path: '/account/change-password'
      fullPath: '/account/change-password'
      preLoaderRoute: typeof AccountChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/account/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/utilities': {
      id: '/account/utilities'
      path: '/account/utilities'
      fullPath: '/account/utilities'
      preLoaderRoute: typeof AccountUtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mailings': {
      id: '/admin/mailings'
      path: '/admin/mailings'
      fullPath: '/admin/mailings'
      preLoaderRoute: typeof AdminMailingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/premises': {
      id: '/admin/premises'
      path: '/admin/premises'
      fullPath: '/admin/premises'
      preLoaderRoute: typeof AdminPremisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/admin/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utilities': {
      id: '/admin/utilities'
      path: '/admin/utilities'
      fullPath: '/admin/utilities'
      preLoaderRoute: typeof AdminUtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$slug': {
      id: '/objects/$slug'
      path: '/objects/$slug'
      fullPath: '/objects/$slug'
      preLoaderRoute: typeof ObjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/documents/$id': {
      id: '/account/documents/$id'
      path: '/account/documents/$id'
      fullPath: '/account/documents/$id'
      preLoaderRoute: typeof AccountDocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents/upload': {
      id: '/admin/documents/upload'
      path: '/upload'
      fullPath: '/admin/documents/upload'
      preLoaderRoute: typeof AdminDocumentsUploadRouteImport
      parentRoute: typeof AdminDocumentsRoute
    }
    '/admin/premises/upload': {
      id: '/admin/premises/upload'
      path: '/upload'
      fullPath: '/admin/premises/upload'
      preLoaderRoute: typeof AdminPremisesUploadRouteImport
      parentRoute: typeof AdminPremisesRoute
    }
  }
}

interface AdminDocumentsRouteChildren {
  AdminDocumentsUploadRoute: typeof AdminDocumentsUploadRoute
}

const AdminDocumentsRouteChildren: AdminDocumentsRouteChildren = {
  AdminDocumentsUploadRoute: AdminDocumentsUploadRoute,
}

const AdminDocumentsRouteWithChildren = AdminDocumentsRoute._addFileChildren(
  AdminDocumentsRouteChildren,
)

interface AdminPremisesRouteChildren {
  AdminPremisesUploadRoute: typeof AdminPremisesUploadRoute
}

const AdminPremisesRouteChildren: AdminPremisesRouteChildren = {
  AdminPremisesUploadRoute: AdminPremisesUploadRoute,
}

const AdminPremisesRouteWithChildren = AdminPremisesRoute._addFileChildren(
  AdminPremisesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FavoritesRoute: FavoritesRoute,
  RentRoute: RentRoute,
  SaleRoute: SaleRoute,
  ServicesRoute: ServicesRoute,
  AccountActivateRoute: AccountActivateRoute,
  AccountChangePasswordRoute: AccountChangePasswordRoute,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountUtilitiesRoute: AccountUtilitiesRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminDocumentsRoute: AdminDocumentsRouteWithChildren,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMailingsRoute: AdminMailingsRoute,
  AdminPremisesRoute: AdminPremisesRouteWithChildren,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminStatisticsRoute: AdminStatisticsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminUtilitiesRoute: AdminUtilitiesRoute,
  ObjectsSlugRoute: ObjectsSlugRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  AccountDocumentsIdRoute: AccountDocumentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
