import { createHash, createHmac, randomUUID } from "node:crypto";
import { and, eq, inArray, sql } from "drizzle-orm";
import { getDatabase } from "@/server/db/client";
import * as s from "@/server/db/schema";
import { createOpaqueToken, hashToken } from "@/server/portal/security";
import { requirePermission } from "@/server/portal/portal.server";

export const ADMIN_SECTIONS = [
  ["/admin/premises", "Помещения", "premises.manage"], ["/admin/tenants", "Арендаторы", "tenants.manage"],
  ["/admin/leads", "Потенциальные клиенты", "leads.manage"], ["/admin/requests", "Заявки", "requests.view"],
  ["/admin/mailings", "Рассылки", "mailings.manage"], ["/admin/announcements", "Объявления", "announcements.manage"],
  ["/admin/documents", "Документы", "documents.manage"], ["/admin/services", "Дополнительные услуги", "services.manage"],
  ["/admin/ads", "Реклама арендаторов", "ads.manage"], ["/admin/support", "Поддержка", "support.manage"],
  ["/admin/employees", "Сотрудники", "employees.manage"], ["/admin/statistics", "Статистика", "statistics.view"],
] as const;

export async function adminNavigation() {
  const user = await requirePermission("admin.access");
  return { user, sections: ADMIN_SECTIONS.filter(([, , permission]) => user.roles.includes("admin") || user.permissions.includes(permission)) };
}

export async function employeesAdmin() {
  await requirePermission("employees.manage");
  const db = getDatabase();
  const users = await db.select({ id:s.users.id,name:s.users.displayName,email:s.users.email,active:s.users.isActive,jobTitle:s.employees.jobTitle })
    .from(s.users).innerJoin(s.employees,eq(s.employees.userId,s.users.id)).orderBy(s.users.displayName);
  const links = await db.select({ userId:s.userRoles.userId,role:s.roles.code }).from(s.userRoles).innerJoin(s.roles,eq(s.userRoles.roleId,s.roles.id));
  const roles = await db.select({ id:s.roles.id,code:s.roles.code,name:s.roles.name }).from(s.roles).where(sql`${s.roles.code}<>'tenant'`).orderBy(s.roles.name);
  return { employees: users.map(u=>({...u,roles:links.filter(x=>x.userId===u.id).map(x=>x.role)})),roles };
}

export async function saveEmployeeAdmin(input:{id?:string;name:string;email:string;jobTitle?:string;active:boolean;roleCodes:string[]}) {
  const actor=await requirePermission("employees.manage"); const db=getDatabase(); const id=input.id||randomUUID();
  const allowed=await db.select({id:s.roles.id,code:s.roles.code}).from(s.roles).where(inArray(s.roles.code,input.roleCodes));
  if(!allowed.length||allowed.some(r=>r.code==="tenant")) throw new Error("Выберите роль сотрудника");
  let token:string|undefined;
  await db.transaction(async tx=>{
    if(input.id) await tx.update(s.users).set({displayName:input.name,email:input.email.trim().toLowerCase(),isActive:input.active,updatedAt:new Date()}).where(and(eq(s.users.id,id),eq(s.users.kind,"employee")));
    else { await tx.insert(s.users).values({id,kind:"employee",displayName:input.name,email:input.email.trim().toLowerCase(),isActive:input.active}); token=createOpaqueToken(); await tx.insert(s.userAccessTokens).values({id:randomUUID(),userId:id,purpose:"activation",tokenHash:hashToken(token),expiresAt:new Date(Date.now()+72*3600000)}); }
    await tx.insert(s.employees).values({id:`employee-${id}`,userId:id,jobTitle:input.jobTitle||null}).onConflictDoUpdate({target:s.employees.userId,set:{jobTitle:input.jobTitle||null,updatedAt:new Date()}});
    await tx.delete(s.userRoles).where(eq(s.userRoles.userId,id)); await tx.insert(s.userRoles).values(allowed.map(r=>({userId:id,roleId:r.id})));
    if(!input.active) await tx.update(s.userSessions).set({revokedAt:new Date()}).where(and(eq(s.userSessions.userId,id),sql`${s.userSessions.revokedAt} is null`));
    await tx.insert(s.auditLogs).values({id:randomUUID(),actorUserId:actor.id,action:input.id?"employee.updated":"employee.created",entityType:"user",entityId:id,after:{roles:input.roleCodes,active:input.active}});
  });
  if(token){const {sendAccessEmail}=await import("@/server/portal/email.server");await sendAccessEmail({email:input.email,name:input.name,token,purpose:"activation"});}
  return {id};
}

export async function premisesAdmin() {
  await requirePermission("premises.manage"); const db=getDatabase();
  const premises=await db.select({id:s.premises.id,title:s.premises.title,slug:s.premises.slug,address:s.propertyObjects.address,objectId:s.premises.objectId,typeId:s.premises.typeId,statusId:s.premises.statusId,area:s.premises.areaSqm,release:s.premises.expectedReleaseOn,publication:s.premises.publicationStatus,rent:s.propertyOffers.rentPricePerSqm,sale:s.propertyOffers.salePrice})
    .from(s.premises).innerJoin(s.propertyObjects,eq(s.premises.objectId,s.propertyObjects.id)).leftJoin(s.propertyOffers,eq(s.propertyOffers.premiseId,s.premises.id)).orderBy(s.premises.title);
  return {premises,objects:await db.select({id:s.propertyObjects.id,name:s.propertyObjects.name}).from(s.propertyObjects),types:await db.select({id:s.premiseTypes.id,name:s.premiseTypes.name}).from(s.premiseTypes),statuses:await db.select({id:s.premiseStatuses.id,name:s.premiseStatuses.name}).from(s.premiseStatuses)};
}

export async function savePremiseAdmin(input:{id?:string;title:string;slug:string;objectId:string;typeId:string;statusId?:string;area?:string;release?:string;publication:"draft"|"published"|"archived";offerType:"rent"|"sale";price?:string}) {
  const actor=await requirePermission("premises.manage"); const db=getDatabase(); const id=input.id||randomUUID();
  await db.transaction(async tx=>{
    const before=input.id?(await tx.select().from(s.premises).where(eq(s.premises.id,id)).limit(1))[0]:null;
    if(input.id) await tx.update(s.premises).set({title:input.title,slug:input.slug,objectId:input.objectId,typeId:input.typeId,statusId:input.statusId||null,areaSqm:input.area||null,expectedReleaseOn:input.release||null,publicationStatus:input.publication,updatedAt:new Date()}).where(eq(s.premises.id,id));
    else await tx.insert(s.premises).values({id,title:input.title,slug:input.slug,objectId:input.objectId,typeId:input.typeId,statusId:input.statusId||null,areaSqm:input.area||null,expectedReleaseOn:input.release||null,publicationStatus:input.publication,sourceSystem:"manual",externalId:`admin:${id}`});
    await tx.insert(s.propertyOffers).values({id:`offer-${id}-${input.offerType}`,premiseId:id,type:input.offerType,publicationStatus:input.publication,rentPricePerSqm:input.offerType==="rent"?(input.price||null):null,salePrice:input.offerType==="sale"?(input.price||null):null}).onConflictDoUpdate({target:[s.propertyOffers.premiseId,s.propertyOffers.type],set:{publicationStatus:input.publication,rentPricePerSqm:input.offerType==="rent"?(input.price||null):null,salePrice:input.offerType==="sale"?(input.price||null):null,updatedAt:new Date()}});
    await tx.insert(s.auditLogs).values({id:randomUUID(),actorUserId:actor.id,action:input.id?"premise.updated":"premise.created",entityType:"premise",entityId:id,before,after:input});
  }); return {id};
}

export async function premiseMediaAdmin(premiseId:string){await requirePermission("premises.manage");return getDatabase().select({id:s.mediaAssets.id,url:s.mediaAssets.publicUrl,title:s.mediaAssets.title,kind:s.mediaAssets.kind,order:s.premiseMedia.sortOrder}).from(s.premiseMedia).innerJoin(s.mediaAssets,eq(s.premiseMedia.mediaId,s.mediaAssets.id)).where(eq(s.premiseMedia.premiseId,premiseId)).orderBy(s.premiseMedia.sortOrder);}
export async function updatePremiseMediaAdmin(input:{premiseId:string;mediaId:string;action:"main"|"up"|"down"|"remove"}){const actor=await requirePermission("premises.manage");const db=getDatabase();const rows=await premiseMediaAdmin(input.premiseId);const index=rows.findIndex(x=>x.id===input.mediaId);if(index<0)throw new Error("Медиа не найдено");if(input.action==="remove")await db.delete(s.premiseMedia).where(and(eq(s.premiseMedia.premiseId,input.premiseId),eq(s.premiseMedia.mediaId,input.mediaId)));else{const target=input.action==="main"?0:input.action==="up"?Math.max(0,index-1):Math.min(rows.length-1,index+1);const reordered=[...rows];const [item]=reordered.splice(index,1);reordered.splice(target,0,item!);await db.transaction(async tx=>{for(const [order,row] of reordered.entries())await tx.update(s.premiseMedia).set({sortOrder:order}).where(and(eq(s.premiseMedia.premiseId,input.premiseId),eq(s.premiseMedia.mediaId,row.id)));});}await db.insert(s.auditLogs).values({id:randomUUID(),actorUserId:actor.id,action:`premise_media.${input.action}`,entityType:"premise",entityId:input.premiseId,after:{mediaId:input.mediaId}});}

function hmac(key:Buffer|string,value:string){return createHmac("sha256",key).update(value).digest();}
export async function uploadPremiseMediaAdmin(input:{premiseId:string;file:File;role:"photo"|"video"}){await requirePermission("premises.manage");if(input.file.size<1||input.file.size>100*1024*1024)throw new Error("Файл должен быть до 100 МБ");const env={endpoint:process.env.S3_ENDPOINT!,bucket:process.env.S3_BUCKET!,access:process.env.S3_ACCESS_KEY_ID!,secret:process.env.S3_SECRET_ACCESS_KEY!};if(Object.values(env).some(x=>!x))throw new Error("S3 не настроен");const bytes=Buffer.from(await input.file.arrayBuffer());const checksum=createHash("sha256").update(bytes).digest("hex");const duplicate=(await getDatabase().select({id:s.mediaAssets.id}).from(s.mediaAssets).where(eq(s.mediaAssets.checksumSha256,checksum)).limit(1))[0];let mediaId=duplicate?.id;if(!mediaId){mediaId=randomUUID();const ext=(input.file.name.split(".").pop()||"bin").replace(/[^a-z0-9]/gi,"").toLowerCase();const key=`admin/${input.premiseId}/${checksum.slice(0,24)}.${ext}`;const endpoint=new URL(env.endpoint);const now=new Date(),stamp=now.toISOString().replace(/[:-]|\.\d{3}/g,"").slice(0,15)+"Z",day=stamp.slice(0,8),region="ru-1",payload=checksum,uri=`/${env.bucket}/${key}`,type=input.file.type||"application/octet-stream",headers=`content-type:${type}\nhost:${endpoint.host}\nx-amz-content-sha256:${payload}\nx-amz-date:${stamp}\n`,signed="content-type;host;x-amz-content-sha256;x-amz-date",canonical=["PUT",uri,"",headers,signed,payload].join("\n"),scope=`${day}/${region}/s3/aws4_request`,toSign=["AWS4-HMAC-SHA256",stamp,scope,createHash("sha256").update(canonical).digest("hex")].join("\n"),signing=hmac(hmac(hmac(hmac(`AWS4${env.secret}`,day),region),"s3"),"aws4_request"),signature=createHmac("sha256",signing).update(toSign).digest("hex");const response=await fetch(`${env.endpoint.replace(/\/$/,"")}${uri}`,{method:"PUT",body:bytes,headers:{"content-type":type,"x-amz-content-sha256":payload,"x-amz-date":stamp,authorization:`AWS4-HMAC-SHA256 Credential=${env.access}/${scope}, SignedHeaders=${signed}, Signature=${signature}`}});if(!response.ok)throw new Error(`S3 HTTP ${response.status}`);await getDatabase().insert(s.mediaAssets).values({id:mediaId,kind:input.role==="video"?"video":"image",storageKey:key,publicUrl:`${env.endpoint.replace(/\/$/,"")}/${env.bucket}/${key}`,title:input.file.name,mimeType:type,byteSize:bytes.length,checksumSha256:checksum,metadata:{role:input.role,source:"admin"}});}const max=(await getDatabase().select({value:sql<number>`coalesce(max(${s.premiseMedia.sortOrder}),-1)`}).from(s.premiseMedia).where(eq(s.premiseMedia.premiseId,input.premiseId)))[0]?.value??-1;await getDatabase().insert(s.premiseMedia).values({premiseId:input.premiseId,mediaId,sortOrder:Number(max)+1}).onConflictDoNothing();return {mediaId};}

export async function adminOperations(section:string){const permission:{[k:string]:string}={leads:"leads.manage",mailings:"mailings.manage",announcements:"announcements.manage",services:"services.manage",ads:"ads.manage",support:"support.manage",statistics:"statistics.view"};await requirePermission(permission[section]||"admin.access");const db=getDatabase();if(section==="leads")return db.select({id:s.propertyInterests.id,title:s.propertyInterests.contactName,detail:s.propertyInterests.contactPhone,note:s.propertyInterests.note,createdAt:s.propertyInterests.createdAt}).from(s.propertyInterests).orderBy(sql`${s.propertyInterests.createdAt} desc`);if(section==="announcements"||section==="mailings")return db.select({id:s.announcements.id,title:s.announcements.title,detail:s.announcements.body,createdAt:s.announcements.createdAt}).from(s.announcements).orderBy(sql`${s.announcements.createdAt} desc`);if(section==="services")return db.select({id:s.additionalServices.id,title:s.additionalServices.title,detail:s.additionalServices.description,createdAt:s.additionalServices.createdAt}).from(s.additionalServices).orderBy(sql`${s.additionalServices.createdAt} desc`);if(section==="ads")return db.select({id:s.adPlacements.id,title:s.adPlacements.title,detail:s.adPlacements.offerText,createdAt:s.adPlacements.createdAt}).from(s.adPlacements).orderBy(sql`${s.adPlacements.createdAt} desc`);if(section==="support")return db.select({id:s.requests.id,title:s.requests.subject,detail:s.requests.description,createdAt:s.requests.createdAt}).from(s.requests).innerJoin(s.requestDirections,eq(s.requests.directionId,s.requestDirections.id)).where(inArray(s.requestDirections.code,["technical","access","other"])).orderBy(sql`${s.requests.createdAt} desc`);return [{id:"stats",title:"Сводка",detail:JSON.stringify((await db.execute(sql`select (select count(*) from premises) premises,(select count(*) from users where kind='tenant') tenants,(select count(*) from requests) requests,(select count(*) from property_interests) leads`)).rows[0]),createdAt:new Date()}];}

export async function createAdminOperation(input:{section:string;title:string;detail:string;tenantId?:string}){const permission:{[k:string]:string}={leads:"leads.manage",mailings:"mailings.manage",announcements:"announcements.manage",services:"services.manage",ads:"ads.manage"};const actor=await requirePermission(permission[input.section]||"admin.access");const db=getDatabase(),id=randomUUID();if(input.section==="leads"){const premise=(await db.select({id:s.premises.id}).from(s.premises).limit(1))[0];if(!premise)throw new Error("Нет помещений");await db.insert(s.propertyInterests).values({id,premiseId:premise.id,kind:"application",contactName:input.title,note:input.detail});}else if(input.section==="services")await db.insert(s.additionalServices).values({id,title:input.title,description:input.detail});else if(input.section==="ads"){const org=(await db.select({id:s.organizations.id}).from(s.organizations).limit(1))[0];if(!org)throw new Error("Нет организации");await db.insert(s.adPlacements).values({id,organizationId:org.id,title:input.title,offerText:input.detail});}else{await db.insert(s.announcements).values({id,title:input.title,body:input.detail,publishedAt:new Date()});if(input.section==="mailings"){const recipients=input.tenantId?[{id:input.tenantId}]:await db.select({id:s.users.id}).from(s.users).where(and(eq(s.users.kind,"tenant"),eq(s.users.isActive,true)));if(recipients.length)await db.insert(s.notifications).values(recipients.map(u=>({id:randomUUID(),userId:u.id,announcementId:id,title:input.title,body:input.detail,channel:"in_app" as const,deliveredAt:new Date()})));}}await db.insert(s.auditLogs).values({id:randomUUID(),actorUserId:actor.id,action:`${input.section}.created`,entityType:input.section,entityId:id});return{id};}

export async function deleteAdminOperation(input:{section:string;id:string}){const permission:{[k:string]:string}={leads:"leads.manage",mailings:"mailings.manage",announcements:"announcements.manage",services:"services.manage",ads:"ads.manage"};const actor=await requirePermission(permission[input.section]||"admin.access");const db=getDatabase();if(input.section==="leads")await db.delete(s.propertyInterests).where(eq(s.propertyInterests.id,input.id));else if(input.section==="services")await db.delete(s.additionalServices).where(eq(s.additionalServices.id,input.id));else if(input.section==="ads")await db.delete(s.adPlacements).where(eq(s.adPlacements.id,input.id));else await db.delete(s.announcements).where(eq(s.announcements.id,input.id));await db.insert(s.auditLogs).values({id:randomUUID(),actorUserId:actor.id,action:`${input.section}.deleted`,entityType:input.section,entityId:input.id});}
